#!/bin/bash

if [ "$(ps -aux | grep /bin/synergyc | wc -l)" -ge 2 ]; then
    notify-send "Synergy already running"
    exit 1;
fi


HOST="jacksons-desktop"
HOST_STATUS=$(dig $HOST | grep NOERROR | wc -l)

if [ $HOST_STATUS -eq "1" ]; then
    /usr/local/src/synergy-v1.8.8-stable-c30301e-Source/bin/synergyc --enable-crypto -n jacksons-laptop --restart --daemon $HOST
    notify-send "jacksons-desktop found, synergy daemon started"

else
    notify-send "jacksons-desktop not found :("

fi
